# version
#version 1.0
FROM centos:centos7
MAINTAINER qjx

RUN yum install -y readline-devel pcre-devel openssl-devel gcc
RUN mkdir -p /usr/openresty
WORKDIR /usr/openresy
RUN wget https://openresty.org/download/openresty-1.17.8.2.tar.gz
RUN tar -zxvf openresty-1.17.8.2.tar.gz
RUN cd openresty-1.17.8.2




